# Generated by Django 3.2.6 on 2025-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('articulo', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('linea', models.CharField(blank=True, choices=[('HOMBRE', 'Hombre'), ('DAMA', 'Dama'), ('UNISEX', 'Unisex')], max_length=50, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
