# Generated by Django 3.2.6 on 2025-04-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_costo',
        ),
        migrations.AddField(
            model_name='producto',
            name='articulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='linea',
            field=models.CharField(blank=True, choices=[('HOMBRE', 'Hombre'), ('DAMA', 'Dama'), ('UNISEX', 'Unisex')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
