# Generated by Django 3.2.6 on 2025-10-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despachos', '0001_initial'),
        ('ordenes_compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_remision', models.CharField(max_length=20, unique=True)),
                ('fecha_remision', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remisiones', to='ordenes_compra.ordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remision_detalle', to='despachos.despacho')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='remisiones.remision')),
            ],
        ),
    ]
