version: '3.8'
services:
  web:
    # Ejecutar como root en dev evita muchos problemas de permisos al montar desde Windows
    user: "root"
    volumes:
      - .:/app:delegated
      # Mantén static/media en volúmenes separados para no sobreescribirlos con el bind mount
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings
      # Si necesitas variables locales, crea un archivo .env.dev y carga aquí (no incluido en repo)
      # - DATABASE_URL=postgres://postgres:123@db:5432/sintra
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

volumes:
  static_volume:
  media_volume:

# REMOVED: docker-compose.override.yml content removed from repository.
# Use local development instructions from README.md
