# Generated by Django 3.2.6 on 2025-09-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_auto_20250908_1739'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('email_proyecto', models.EmailField(blank=True, max_length=255, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=10, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=255, null=True)),
                ('direccion_proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='clientes.clientes')),
            ],
        ),
    ]
