# Generated by Django 3.2.6 on 2025-09-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_auto_20250908_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('email_cliente', models.EmailField(blank=True, max_length=255, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=10, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=255, null=True)),
                ('direccion_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('tiene_proyectos', models.BooleanField(default=False)),
                ('ciudad_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
            ],
        ),
    ]
