# Generated by Django 3.2.6 on 2025-04-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nombre_cliente',
            field=models.CharField(max_length=255),
        ),
    ]
