# Generated by Django 3.2.6 on 2025-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tiene_proyectos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
