# Generated by Django 3.2.6 on 2025-08-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_tiene_proyectos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tiene_proyectos',
            field=models.BooleanField(default=False),
        ),
    ]
