# Generated by Django 3.2.6 on 2025-04-06 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20250406_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='ciudad',
            new_name='ciudad_cliente',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='direccion',
            new_name='direccion_cliente',
        ),
    ]
