# Generated by Django 3.2.6 on 2025-04-07 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20250406_1913'),
        ('clientes', '0004_auto_20250406_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='ciudad_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
    ]
