# Generated by Django 3.2.6 on 2025-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('reintegro', models.BooleanField(default=False)),
                ('fecha_reintegro', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
