# Generated by Django 3.2.6 on 2025-10-05 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes_compra', '0001_initial'),
        ('despachos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='producto_solicitado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='ordenes_compra.productosolicitado'),
        ),
    ]
