# Generated by Django 3.2.6 on 2025-09-10 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0001_initial'),
        ('despachos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('producto_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='ordenes_compra.productosolicitado')),
            ],
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
