# Generated by Django 3.2.6 on 2025-10-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0002_auto_20250910_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='fecha_reintegro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='reintegro',
            field=models.BooleanField(default=False),
        ),
    ]
