# Generated by Django 3.2.6 on 2025-10-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0003_auto_20251002_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='fecha_despacho',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='fecha_reintegro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
