# Generated by Django 3.2.6 on 2025-10-03 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='usuariorol',
            options={'verbose_name': 'Usuario Rol', 'verbose_name_plural': 'Usuario Roles'},
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='primer_login',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='primer_acceso',
            field=models.BooleanField(default=True, verbose_name='Primer Acceso'),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='perfilusuario',
            table='perfil_usuario',
        ),
        migrations.AlterModelTable(
            name='usuariorol',
            table='usuario_rol',
        ),
    ]
