# Generated by Django 3.2.6 on 2025-07-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='codigo_oc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
